[project]
name = "workspace3"
version = "0.1.0"
description = "A multiroot project with a single environment (workspace3)"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
